name = input("Enter your name: ")
age = input("Enter age: ")
student_class = input("Enter the student class: ")
marks = input("Enter the student mark: ")
print("------Student detail------")
print(f"Name : {name}")
print(f"Age : {age}")
print(f"Student class : {student_class}")
print(f"Marks : {marks}")